name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: |
        sudo apt install -y valgrind
        mkdir -p build/test
        mkdir -p build/types
        make build build-tests
    - name: Testing
      run: make tests memcheck
