name: build

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest   
    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: make build build-tests main
    - name: Testing
      run: make tests
